swimlane/swimlane-python

swimlane/core/auth/user_pass_auth_provider.py, tests/core/auth/test_user_pass_auth_provider.py
I've found that latest release of swimlane-python client version **0.1.0** expects to find session cookie in [**.AspNetCore.Identity.Application**](https://github.com/swimlane/swimlane-python/blob/69b9a648b1f27657ba44e9e14b8eacf2bad8a3a9/swimlane/core/auth/user_pass_auth_provider.py#L13)
But Swimlane API server version **2.10.27** contains session cookie value in **.AspNet.ApplicationCookie** in HTTP response:
> Server: Microsoft-IIS/8.5
> X-AspNet-Version: 4.0.3031
> Set-Cookie: **.AspNet.AppcationCookie**=some_value; path=/; secure; HttpOnly
> X-Powered-By: ASP.NET
So it makes impossible to use latest swimlane python client **0.1.0** with Swimlane API server version **2.10.27**.
=> fix hard-coded session cookie name

requirements.txt, swimlane/core/cache.py, swimlane/core/client.py, tests/conftest.py, tests/test_client.py
* Added automatic reauthentication when JWT is within 5 minutes of expiring whenever a request is about to be sent to Swimlane
* Removed sub-v2.13 login support
* Minor fixes and logging tweaks
Tested with debugger, manually highjacking token expiration date to 6 minutes past initial login time, and repeatedly pulling list of all apps. Verified first call within 5 minutes of faked token expiration waits until token is refreshed as expected, script attached to Jira. 
Can work with QA to verify against Swimlane with lower JWT expiration timeout, wasn't sure where that config was, and didn't want to impact anyone using the same server.
=> PYD-87 Add automatic reauthentication when JWT is about to expire

setup.py, swimlane/core/fields/list.py
Rolled back to pre-4.0.1 changes, should take this PR over those changes. Still need to add unit tests to assert fix, but quick tested in debugger and seems to be working. 
* Backwards compatible, iteration still works over values without exposing IDs
* Numeric and Text field
* Reuses existing IDs for any values already in list
* Keeps existing IDs for sort, reverse, etc. operations, and respects any new ordering
* Respects field lifecycle, IDs restored during save, any modifications done between get and each save don't matter
=> Use existing IDs for any values already in list fields

docs/examples/client.rst, setup.py, swimlane/core/client.py, tests/conftest.py, tests/test_client.py
Adds support for authenticating with Swimlane using a personal access token in place of a username and password.
Updates `SwimlaneClient` to make the `username` and `password` `__init__` params optional, then adds a new optional `access_token` parameter to the end of the parameter list to avoid breaking any existing customer code that uses only positional parameters.
A new `SwimlaneTokenAuth` class has been added to support personal access token authentication in the driver. This class is then used whenever an access token is supplied to `SwimlaneClient` instead of a username and password. When `Requests` invokes the class, a request is then made to `api/user/authorize` with the access token provided as a header in order to validate it and to return information about the user. A [separate …
=> PYD-85 - Update Python driver to support token authentication

setup.py, swimlane/core/client.py, swimlane/core/wrappedsession.py, tests/conftest.py
Wrapping the request session object to work around a request bug when `REQUESTS_CA_BUNDLE` is set.
See https://github.com/kennethreitz/requests/issues/3829 for more info.
=> SPT-4302 SSL Verify fix

docs/examples/client.rst, swimlane/core/client.py, swimlane/core/fields/base/field.py, swimlane/core/fields/text.py, tests/resources/test_record.py
Enables the ability to write to read only fields via a parameter of the driver.  Also added in better handling for json fields.
Updated documentation as well.
=> SPT-4287 Write to read only fields

swimlane/core/fields/base/field.py, swimlane/core/fields/usergroup.py, swimlane/core/fields/valueslist.py, swimlane/core/resources/record.py, tests/resources/test_record.py
Allows for the following interactions with a record:
```
record = app.records.get(tracking_id='5997-1')
record['Existing'] = 'overwrite'
record['ToRemove'] = None
record.patch()
```
Where the call to `.patch()` sends the following payload to the new PATCH endpoint for Record:
```
{
'$type': 'Core.Models.Record.Record, Core',
'id': 'r1',
...
'values': {
'existing-id': 'overwrite',
'remove-id': null
}
}
```
=> [SPT-5997] Add Record PATCH endpoint support

.travis.yml
Updates the travis-ci build to upload the package from the python 2.7 build to S3.
=> SPT-5882: Make travis build upload to s3

swimlane/core/client.py
This will fix the version being in either of the 2 formats that Swimlane has used.
<product_version>+<build_version>+<build_number>
<build_version>+<build_number>
=> SPT-6628 fix version breakdown

functional_tests/requirements.txt
pytest-html supports 2.x through 1.22.1, but does not support 3.8 until later, so settign to a min value of 1.22.1, allowing for newer when using a newer python version.
=> TA-71 fix version of pytest-html

functional_tests/conftest.py
Removing the pytest.fixture calls on the functions for the arguments used in the tests.
=> TA-71 cleanup pytest.fixure

functional_tests/requirements.txt
Removing the dependency to the pip version of the pyDriver, for supporting test against code not released yet.
=> TA-71 removing swimlane dependency

functional_tests/conftest.py
conftest was failing while trying to import an SSP because it expected to get a ContentExchangeResult back instead of a tracking ID. Updated to work post-SPT-10343.
=> SPT-11003: Update import_content to work with new tracking endpoint

functional_tests/conftest.py
Last fix worked by chance - this update will run the import synchronously instead of as a background process (for real this time) and check the correct value in the status endpoint's response to see if it was successful.
=> SPT-11003: Run import synchronously

functional_tests/conftest.py
If logs of the job beiong copmpleted are missed, then there would be an infinite loop, as seen in the test runs. This should prevent it.
=> SPT-12167 do not infinite loop.

functional_tests/driver_tests/test_records_bulk_adaptor.py, swimlane/core/adapters/record.py
Reverts swimlane/swimlane-python#147
These changes has to be reverted as the tests failing in the PR's
=> Revert "Namor/SPT-14498:Bulk record create endpoint does not return a list of created records"

functional_tests/conftest.py, functional_tests/driver_tests/test_record_task_execution.py
SPT-15310 introduced a new parameter to the content/import endpoint which contains a list of the IDs of the entities which should be imported. SPT-15811 adjusted the default behavior for an empty list, and now sending no IDs results in importing no entities. That is a breaking change, and this PR fixes the pydriver tests, which are using an SSP to shortcut test setup but need to include the new parameter in order for anything to be imported.
=> SPT-15811: Send entityIds parameter to SSP import endpoint

requirements.txt, swimlane/core/cache.py, swimlane/core/fields/list.py
I updated some packages to delete all the warnings
I updated the sortedcontainers library to the version 2.4.0 and modified the collections imports.
Evidences:
_**Current:**_
_**Fixed:**_
=> SPT-6995: PyDriver code has deprecated calls that are on their way out.

functional_tests/driver_tests/test_users_groups_adaptor.py, swimlane/core/adapters/usergroup.py
- Add a guard that checks the limit param type for the list() method on both the user and group adapter
- Checks if the limit provided is None or integer, else a ValueError is raised with relevant message
- Updated xfail marked tests
Link to ticket: [SPT-6031](https://swimlane.atlassian.net/browse/SPT-6031)
=> SPT- 6031 (bug) - sends non whole numbers for user limit

swimlane/core/resources/record.py
I updated the library to fix an error that occurs during the patch.
I updated the library to support a patch using a 0 value. Because previously we validated using if not value, but this validation is true when you sent a 0 as a value so I added an additional validation to resolve this issue.
Evidences:
_**Current:**_
https://user-images.githubusercontent.com/100230626/208474722-c774739e-5719-45cc-ac16-f47e9a6b68d4.mov
_**Fixed:**_
https://user-images.githubusercontent.com/100230626/208474146-3a15f1fb-12f6-46b0-a5b6-c0a7d5f933a4.mov
=> SPT-9975: Cannot Set Numeric Field to 0 With Python Driver

functional_tests/driver_tests/test_apps_adaptor.py, functional_tests/driver_tests/test_records_adaptor.py, functional_tests/driver_tests/test_users_groups_adaptor.py, swimlane/core/adapters/app.py, swimlane/core/adapters/record.py, swimlane/core/adapters/usergroup.py
- For the app GET by id and name call, check if lookup value is empty or None, if it is raises a ValueError and returns a specific response
- For the records GET by id and tracking_id call, check if lookup value is empty or None, if it is raises a ValueError and returns a specific response
- For the users GET by id and display_name call, check if lookup value is empty or None, if it is raises a ValueError and returns a specific response
- For the groups GET by id and name call, check if lookup value is empty or None, if it is raises a ValueError and returns a specific response
- Update and add tests to app, records, users and groups adapters
=> SPT-6030: Looking up an app/record/user/group/etc, by name/id/refID/etc fail if the value being used is empty or None

swimlane/core/fields/base/multiselect.py, swimlane/core/fields/valueslist.py
Deleted selection field values can leave records in a state which the driver cannot load. For a single-select or a multi-select field, we cross-reference values with the field definition, and this caused an exception.
The scenario:
- Create an application with a multi-select field which has several options
- Create a record with multiple options selected
- Remove one selection option from the application
- Try to load the record
This change will allow the records to be loaded without out-of-date invalid values. Any valid selections in a multi-select field will still be present.
=> Load records with invalid selection field values

docs/_static/css/navigation.css, docs/conf.py
ISSUE:
Unable to scroll down on the left navigation menu for page https://swimlane-python-driver.readthedocs.io/en/stable/examples/resources.html
Added custom CSS page to add scrollability to Navigation
=> SPT-6107: add navigation scrolling

functional_tests/driver_tests/test_helpers_adaptor.py, swimlane/core/adapters/helper.py, swimlane/utils/str_validator.py
I updated the library to validate all the arguments received in add_comment.
I validate all the arguments received in add_comment, to avoid empty strings or any other type different a string.
Evidences:
_**Current:**_
_**Fixed:**_
=> SPT-6195: Pydriver: add_comment with null or empty message should throw error

functional_tests/driver_tests/test_app_reporting_adaptor.py, functional_tests/driver_tests/test_records_adaptor.py, functional_tests/driver_tests/test_records_bulk_adaptor.py, swimlane/core/adapters/record.py, swimlane/core/resources/report.py, swimlane/utils/__init__.py, tests/adapters/test_record_adapter.py
The validation verifies if primitive types match before doing a search/filter, bulk delete or bulk modify.
Same logic was duplicated inside records and report. If there is a utils/helper file where those two can share logic, that would be nice.
[Link to SPT](https://swimlane.atlassian.net/browse/SPT-6028)
=> SPT-6028 Filtering when the field type does not match the comparison value should throw an error.

functional_tests/driver_tests/test_app_revision_adaptor.py, functional_tests/driver_tests/test_record_revision_adaptor.py, swimlane/core/adapters/app_revision.py, swimlane/core/adapters/record_revision.py, tests/adapters/test_app_revision_adapter.py
- For both the app and records GET revisions call, add guard that checks if revision value is an integer AND greater than 0
- If not, raises a ValueError and returns a specific response
- Update and add tests to both app and records adapter
Link to ticket [SPT-6038](https://swimlane.atlassian.net/browse/SPT-6038), which has a video attached demonstrating functionality
Examples of new error handling
Examples of success
=> SPT-6038 - get call for revision of apps and records does not validate param value

functional_tests/driver_tests/test_helpers_adaptor.py, swimlane/core/adapters/helper.py, swimlane/utils/list_validator.py
- Added check in `add_record_references` to validate that the references list `target_record_ids` contains valid data. Raises a ValueError if validation fails and returns a specific response.
- Update and added tests to `HelperAdapter`.
=> SPT-6241: add_record_references should validate the references list contains valid data

functional_tests/driver_tests/test_helpers_adaptor.py, swimlane/core/adapters/helper.py, swimlane/utils/str_validator.py
I updated the library to validate the argument received in check_bulk_job_status.
I validate the job_id, to avoid empty strings or any other type different a string.
Evidences:
_**Current:**_
_**Fixed:**_
=> SPT:6233 Pydriver: check_bulk_job_status with invalid Ids should throw error

functional_tests/driver_tests/test_app_reporting_adaptor.py, swimlane/core/resources/report.py
- Added check in `_get_stub_field` to validate that `field_name` is of a valid format. Raises a ValueError if validation fails and returns a specific response.
- Updated and added tests to `test_app_reporting_adaptor`.
=> SPT-6305: report.filter(...) should verify field name value

swimlane/core/resolver.py
Changes made handle referents more gracefully by checking if the object is alive and also raising the correct error when the referenced object gets destroyed.
Added everyone as code reviewers because I'm not sure of the process this team has.
=> SPT-8009 SC-5542 fix: added referent failsafe and raise a reference error if destroyed

swimlane/core/fields/base/multiselect.py, swimlane/core/fields/usergroup.py, tests/fields/test_valueslist.py
Hi Team, this PR adds the following:
- Background conversion of not-iterable values to lists in Multiselect fields.
=> fix(SC-5540 SPT-6196): handling not iterable values on multiselect fields

functional_tests/conftest.py, functional_tests/driver_tests/test_attachment_fields.py, functional_tests/driver_tests/test_date_time_fields.py, functional_tests/driver_tests/test_numeric_fields.py, functional_tests/driver_tests/test_record_restriction_adaptor.py, functional_tests/driver_tests/test_records_bulk_adaptor.py, functional_tests/driver_tests/test_records_readonly_overwrite.py, functional_tests/driver_tests/test_selection_fields.py, functional_tests/driver_tests/test_text_fields.py, functional_tests/driver_tests/test_user_group_fields.py, swimlane/core/adapters/helper.py, swimlane/core/adapters/record.py, swimlane/core/cache.py, swimlane/core/fields/base/field.py, swimlane/core/fields/comment.py, swimlane/core/fields/list.py, swimlane/core/fields/number.py, swimlane/core/fields/reference.py, swimlane/core/fields/usergroup.py, swimlane/core/resources/app.py, swimlane/core/resources/record.py, swimlane/core/resources/usergroup.py, swimlane/utils/__init__.py
For error messages, we are using multiple types of quotes for quoting substrings within the string.
Examples: 
- `raise ValueError('The value provided for the key "{0}" cannot be empty or None'.format(key))`
- `raise ValueError("Field '{}' of Type '{}', is not supported for bulk modify".format()`
We should standardize on a format and use the first example as our standard.
Examples:
- `raise ValueError('This is an error')`
- `raise ValueError('This is an error with the following message: "{}"'.format('message')`
=> SPT-6341: Standardize quoting styles in error messages

swimlane/core/resources/report.py
I fixed the search function to accept '' as a default value for text list field.
I repaired the text list field search because now we accept None or '' as a default value when we are looking for a record.
Evidences:
_**Current:**_
https://user-images.githubusercontent.com/100230626/221235423-dca4b3d4-fed6-4389-aced-faf68e56dbd7.mov
_**Fixed:**_
https://user-images.githubusercontent.com/100230626/221030504-0e5d3388-a227-45ff-98a6-273cd57fdb01.mov
Tests:
=> SPT-6525: Python Driver Should Evaluate an Empty String to None

functional_tests/driver_tests/test_records_bulk_adaptor.py
Removed `xfail` from tests:
- `test_record_bulk_modify_remove_text_list`
- `test_record_bulk_modify_remove_numeric_list`
Tests should pass once [this PR](https://github.com/swimlane/swimlane/pull/2410) is merged.
=> SPT-7929: Bulk modify of text or numeric list does not remove the item if it is the only one left

functional_tests/driver_tests/test_history_fields.py, swimlane/core/resources/record_revision.py, swimlane/core/resources/revision_base.py
I updated the pyDriver to throw an error when you try to set an not editable field.
I updated the pythonDriver to throw an exception when you try to edit an not editable field.
Evidences:
_**Current:**_
https://user-images.githubusercontent.com/100230626/220434261-0e4db935-ba07-4a80-9985-47832b49a619.mov
_**Fixed:**_
https://user-images.githubusercontent.com/100230626/220433846-df85ed4d-2530-4799-bb49-5a727b2586c7.mov
Tests:
_**Current:**_
_**Fixed:**_
=> fix: All attributes for an element of the history field should report not being editable.

swimlane/core/fields/usergroup.py
I updated the validation process because I need to get the entire user to retrieve the groups data.
I added a line to verify if the user has the groups field if not we are going to get all the user data to verify it.
Evidences:
_**Current:**_
https://user-images.githubusercontent.com/100230626/219811229-08aa0c5e-862b-44bc-9807-082b8e1e3ee9.mov
_**Fixed:**_
https://user-images.githubusercontent.com/100230626/219811422-06ce66dd-f4de-4e24-a391-8cc0337befc9.mov
Tests:
=> SPT-6533: userGroup Field with value set to members of a group does not allow adding users to the field.

swimlane/core/adapters/record.py, swimlane/core/resources/report.py
I updated the library to support 'or' operator on record search.
I modified the pydriver to support 'or' conditions when you try to search records, but by default the operator is 'and'.
Evidences:
_**Current:**_
With 'or' and kwarg:
With kwarg:
With one filter:
Testing:
_**Fixed:**_
With 'or' and kwarg:
With kwarg:
With one filter:
With default operator:
Testing:
Validate operator:
=> SPT-17728: Add Support for "or" operator Record Search Feature.

functional_tests/driver_tests/test_records_bulk_adaptor.py
I fixed a flaky test case.
This issue was casued by a random int that we're using as a record value, the error occurs when we get at least 2 equal random numbers so when we evaluate this test case the value expected change because there are another test case that is making changes, so I decided to get all the random number in the begining of the file using a method to be sure that they aren’t  duplicated value.clea
Evidences:
_**Current:**_
https://user-images.githubusercontent.com/100230626/231184677-c1f1e332-540f-48aa-ba2e-c2f42e727614.mov
_**Fixed:**_
https://user-images.githubusercontent.com/100230626/231183827-43872956-5139-473e-a26f-0da527ef8ada.mov
_All steps are required, when applicable. ~Strikeout~ …
=> SPT-18146: repair flaky test case
