swimlane/swimlane-python

swimlane/core/resources/record.py
Adding a method to add a reference to an existing record.
=> SW-4750 Adding a method for the new add reference route

swimlane/exceptions.py
@nick-allen, I added new error code in platform-dotnet/api (swimlane/platform-dotnet#14).
=> SPT-1352 Add error code of PathNotFound when validating LoggerSettings.

swimlane/exceptions.py
Adding new error code for wrong or missing $type that can be returned by the server post 2.17.
=> SPT-1886 Adding wrong type error code

tests/adapters/test_helper_adapter.py
=> Add coverage to PYD-44

.pylintrc, docs/examples/resources.rst, swimlane/core/adapters/record.py, swimlane/core/bulk.py, swimlane/core/fields/base/field.py, swimlane/core/fields/list.py, swimlane/core/fields/valueslist.py, tests/adapters/test_record_adapter.py, tests/fields/test_list.py
* Fix list field bulk modify
* Move bulk_modify field value casting out of adapter function into field classes
* Add support for append/remove/clear bulk modify operations
* Doc updates for bulk modify
* Remove previously deprecated create_batch function
=> PYD-88 list field bulk modify

swimlane/exceptions.py
Adding new 5017 server error code for invalid server deployed OS, as well as adding missed error codes.
=> SPT-3441 Adding new error codes

setup.py, swimlane/core/fields/list.py
Reverts swimlane/swimlane-python#50
=> Revert "SPT-3889 existing ListField items fix"

swimlane/core/resources/record.py, tests/resources/test_record.py
...so that json serializers in dotnet deserialize UserGroupSelection / ValuesListSelection correctly
=> [SPT-5997] Add $type to PATCH values

setup.py
Updating version number to 10.1.0rc1 for release testing
=> Updating version for RC testing

setup.py
Need to retag to point to new commit so ensuring version numbers are in-sync
=> SPT-6208 updating version to match new tag

setup.py
Update version number for 10.1.0 release
=> Updating version number for release

swimlane/exceptions.py
I added this error code in [SPT-6000](https://swimlane.atlassian.net/browse/SPT-6000).
=> SPT-6000 added SectioNameTooLong to list of exceptions

swimlane/exceptions.py, test-requirements.txt
Adding the error code for new uniqueness constraint on Asset Name's
=> SPT-6809: Adding Duplicate Asset Name error code

.gitignore, functional_tests/conftest.py, functional_tests/pytest.ini, functional_tests/requirements.txt
Adding the hooks and data for junit and html reporting.
=> TA-71 add functional test reporting

functional_tests/driver_tests/test_reporting_filters.py
fixing a random failure where the order of the list changes.
=> TA-71 fix random failure

swimlane/exceptions.py
Added the HangfireError code in the exception list. Introduced in https://github.com/swimlane/platform/pull/683
=> SPT-6399: Added the HangfireError code in the exception list

functional_tests/driver_tests/test_app_reporting_adaptor.py
This was fixed in SPT-6576.
Verified the fix by enabling the test.
=> SPT-6296 fix report listing

.travis.yml
Change the encrypted github key to what was set automatically by `travis setup releases --org -t --force`
=> Change the encrypted github key

functional_tests/driver_tests/test_records_bulk_adaptor.py
Added internal JIRA tickets for the skipped tests in the pyDriver.
=> SPT-6603 adding SPTs to skipped tests.

setup.py
=> (release): 10.3.0

.github/workflows/release.yml, offline_installer/build.py
Removes the windows steps from the release process
=> Remove windows release steps

functional_tests/conftest.py
Extendidn the timeout to 30 seconds and also tracking if the batch job fails.
=> SPT-12167 Exteneding the timeout and tracking failure

.github/workflows/build_test.yml, requirements.txt, swimlane/core/client.py
=> Bump pyjwt; remove Python 2.7 build workflow

swimlane/core/fields/reference.py, tests/fields/test_reference.py
- Treat single reference field the same way as platform does. (AR-2045)
=> SPT-14006: Single reference field as array

swimlane/core/adapters/record.py
Reverts swimlane/swimlane-python#144
=> Revert "SPT-14498: Bulk record create endpoint does not return a list of crea…"

.github/workflows/build_test.yml, swimlane/core/fields/attachment.py, swimlane/core/resources/attachment.py, tests/fields/test_attachment.py
Use non-deprecated attachment download endpoint
=> Update attachment endpoint

docs/examples/fields.rst
Adding valid values as examples to the textfield documentation
=> Adding examples for the text fields

swimlane/core/fields/attachment.py, swimlane/core/resources/record.py
I repaired the attachment save process.
I repaired the attachment save process. Because we were getting the data using a wrong way so I validate if the value has a property elements if it’s there I will use this data.
Evidences:
_**Current:**_
https://user-images.githubusercontent.com/100230626/220950906-bfb721d0-37f5-462b-8677-fa41aeea5c71.mov
_**Fixed:**_
https://user-images.githubusercontent.com/100230626/220945636-fb0829ee-bc0c-4fc0-beae-ffd925441bba.mov
Tests:
_**Current:**_
_**Fixed:**_
=> SPT-17321: Failing to save attachment using new version of python driver

functional_tests/driver_tests/test_text_fields.py
This reverts commit ede3d3442c17b166362cd14d350b58e61911deda.
=> Revert "Updates Comment Test (#205)"

swimlane/core/fields/base/field.py
Jira - https://swimlane.atlassian.net/browse/SPT-29156
=> fix(SPT-32187): added error message for record.search
